# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c714b63475ce28715024d0b32b3c3e2d411c615967892e6d53416bbe8bb5142f6ec8556e14002e73fe8f0f6544d403982c9608f7cd0bed6ad10cdf01f218d07

test:
  secret_key_base: 1d34987d44256dc7f0ae720e4b3272ec6828150ff96711150c3bd720043e12d6f20173af81c70e9321258dca1f86e16ea9e504254ac1bc174546de3d3b969ed4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
